name: Build
on:
  - push
jobs:
  build:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install SBCL
        run: sudo apt-get update && sudo apt-get install sbcl

      - name: Let ASDF find the project
        run: mkdir ~/common-lisp; ln -s `pwd` ~/common-lisp/lcm

      - name: Build
        run: make

      - name: Assert binary exists
        run: test -f lcm